### ISSUE TITLE
tapping sometimes not detected

### ISSUE THREAD

**Issue by khallouki** [zacwest/ZSWTappableLabel#15]
I have a uitableviewcell which contains a ZSWTappableLabel. Some cells contain a tappable word but they are not always detected. But if I click on a tappable word that can be detected and the detecting is fired suddenly all of the words are working and everything is fine.

**Comment by zacwest** [comment]
Do you have any sample code I could see to reproduce this issue? Is the `ZSWTappableLabel` the frontmost view in the cell? Do you have any other gesture recognizers that might be interfering/affecting behavior?

**Comment by khallouki** [comment]
there are other gesture recognizers on the uitableviewcell level, but if I disable them it still isn't solved.
what piece of code do you need?

**Comment by khallouki** [comment]
do you have teamviewer? maybe you can take a look with me if you have time

**Comment by zacwest** [comment]
Sorry, I'm not going to be able to help you with your code base, but if you provide a sample project which replicates the problem I can fix the issue for you.

Basically I need the `NSAttributedString` which reproduces it, and the `UITableViewCell` and its hierarchy which reproduces it as well.

**Comment by zacwest** [comment]
Without an example of the issue reported, I won't be able to make any progress, sorry. Feel free to provide context later on and we can reopen.

**Comment by khallouki** [comment]
Hi,

Thank you for replying. I managed to fix it using the zswtaggedstring.

**Comment by zacwest** [comment]
I'm glad it worked out! Thanks for following up.
