### ISSUE TITLE
Provide support for 3D Touch

### ISSUE THREAD

**Issue by zacwest** [zacwest/ZSWTappableLabel#19]
I believe the API just gives you a CGPoint so we may need to provide a public getter for the attributes at a point like the `-gestureRecognizerShouldBegin:` uses.

Need to make sure the gesture recognizers aren't firing at the same time, so we don't smash state around, since they explicitly depend on the UIGR flow for whether the NSLayoutManager & cousins live.

**Comment by phillebaba** [comment]
A solution would be to expand the existing delegate methods to forward the UITouch methods, which would be called before the tap completes.

**Comment by zacwest** [comment]
I think the problem there is the API for 3D Touch is:

``` swift
func previewingContext(_ previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController?
```

The UIViewController is queried at time of interest with "what's the UIViewController I should present for this _point_?" It would probably be pretty complicated to make the delegates keep track of state for this.
