### ISSUE TITLE
Accessibility frames are off

### ISSUE THREAD

**Issue by kmaschke85** [zacwest/ZSWTappableLabel#21]
Thanks of this great enhancement of UILabel!
While working with it I observed problems with the frames of the accessibility elements. So far I didn't found out the cause, but at least I found a typo in your code that might have something to do with it. But fixing the typo didn't help.
On ZSWTappableLabel.m method performWithLayoutManager in lines 185 and 193 there is a block defined/used called `sreenFrameForCharacterRange`. I think it should be named `screenFrameForCharacterRange`like the method's parameter does. 
As you can see in the screenshots the displayed accessibility frames do not fit the text elements.
Would be nice if you could have a look at it. Thanks!

**Edit:** This might be related to issue #20 .
![simulator screen shot 12 07 2016 15 31 41](https://cloud.githubusercontent.com/assets/16348228/16768908/a03a30d8-4846-11e6-94ca-683436da50eb.png)
![simulator screen shot 12 07 2016 15 31 49](https://cloud.githubusercontent.com/assets/16348228/16768910/a0675324-4846-11e6-9628-a150f749d5d0.png)
![simulator screen shot 12 07 2016 15 32 01](https://cloud.githubusercontent.com/assets/16348228/16768909/a0671f08-4846-11e6-8d88-13072fcd47e0.png)
![simulator screen shot 12 07 2016 15 32 10](https://cloud.githubusercontent.com/assets/16348228/16768912/a06b9a74-4846-11e6-9c2e-5db37f0e833e.png)
![simulator screen shot 12 07 2016 15 32 15](https://cloud.githubusercontent.com/assets/16348228/16768911/a0693d92-4846-11e6-9567-df8bb05849fc.png)

**Comment by zacwest** [comment]
Could you describe what your view hierarchy looks like? Is it a ZSWTappableLabel embedded in a UIScrollView?

**Comment by kmaschke85** [comment]
Yes, the ZSWTappableLabel is inside a UIScrollView, actually it is in a UICollectionView. The ZSWTappableLabel is a subview of a UICollectionViewCell.

**Comment by zacwest** [comment]
Can you confirm which version of the label you're using?

**Comment by kmaschke85** [comment]
I'm using version 1.3 of the pod.

**Comment by kmaschke85** [comment]
Just debugged a bit. As soon as I remove adding the pointOffset to the viewFrame (lines 188-189 in sreenFrameForCharacterRange block) the frames of the first lines now look perfect. While debugging I mentioned that UIAccessibilityElements are  also created for text blocks that only contain whitespace and/or newline characters. I added code to skip these character ranges, because it doesn't make sense to have an accessible element with no readable content. With further investigations I think the frame problem is related to carriage returns and line feeds. It is just the y position that is a number of full lines of. In the first screenshot you can see that the frame is one line bigger then it should be. The next frame begins one line too late and ends three lines too late. The last screenshot shows that the displayed frame belongs to the line three lines above. So my best guess is that it has to have something to do with line breaks. Hope this helps!
![simulator screen shot 13 07 2016 08 34 40](https://cloud.githubusercontent.com/assets/16348228/16794013/706fffd8-48d5-11e6-9aec-5631d799a5bb.png)
![simulator screen shot 13 07 2016 08 35 10](https://cloud.githubusercontent.com/assets/16348228/16794011/706e5318-48d5-11e6-9d0f-8febaa213f5a.png)
![simulator screen shot 13 07 2016 08 35 21](https://cloud.githubusercontent.com/assets/16348228/16794012/706e8270-48d5-11e6-883f-09be0386254c.png)
