### ISSUE TITLE
Regarding accessibility container

### ISSUE THREAD

**Issue by cojoj** [zacwest/ZSWTappableLabel#24]
I'm using your awesome library in my project and I'm really happy that I didn't have to write this on my own. It works perfectly 💯

I have one question regarding **accessibility**. As I can read in `README`:
> `ZSWTappableLabel` is an accessibility container, which exposes the substrings in your attributed string as distinct elements.

It works great, but I was wondering if it's possible to do it a little bit differently? Cause in some cases it feels unnatural for the disabled user to go through all those separate elements. And maybe this isn't the biggest thing, but the case with _cutting_ string into substrings may lead to some confusions.
I'm not sure if it's possible to have nested accessibility labels and still be able to access them, but this would be a perfect solution. Or at least to have access to those separate things and merge a couple of them together. I don't have a clue how I can access those separate elements of accessibility.

For example. Considering we have text like this one:
> Liebe Kunde! Wir haben euch auch sehr vermisst 😚 Nutzt doch einfach den **#feedback** , falls ihr etwas zu meiner Rückkehr sagen wollt! In Liebe, Eure Hashtags #️⃣#️⃣#️⃣

It'll generate array of following accessibility elements:
```swift
["Liebe Kunde! Wir haben euch auch sehr vermisst 😚 Nutzt doch einfach den", "#feedback", ", falls ihr etwas zu meiner Rückkehr sagen wollt! In Liebe, Eure Hashtags", "#️⃣", "#️⃣#️⃣"]
```

**Comment by zacwest** [comment]
Sorry for not responding before, but my reasoning for this behavior is that it is similar behavior to how Safari treats elements in the same situation. I do not wish to change this behavior.
