### ISSUE TITLE
Foreground color on link

### ISSUE THREAD

**Issue by iKisliy** [zacwest/ZSWTappableLabel#30]
When I set foreground color on link, it's still blue

        atrString.addAttributes(
            [
                .tappableRegion: true,
                NSAttributedStringKey.underlineStyle :NSUnderlineStyle.styleThick.rawValue,
             NSAttributedStringKey.underlineColor : UIColor.vaiUnderline,
             NSAttributedStringKey.foregroundColor : UIColor.vaiUnderline,
             .link : urlTerms],
            range: ns2)
        termsLabel.attributedText = atrString

**Comment by iKisliy** [comment]
It's simulator issue, on real device everything is ok

**Comment by iKisliy** [comment]
Found that it's not simulator issue. On iOS 10 — 10.3 it's changing foreground color, but on 11.2+ (11.0?) it's always blue. Someone notice that behavior and how to fix it?

**Comment by YuryRadchenko** [comment]
Did anybody decide the trouble with a blue link color?

**Comment by iKisliy** [comment]
@YuryRadchenko check example, SimpleSwiftViewController.swift and MultipleSwiftViewController.swift

**Comment by OrWest** [comment]
Label is blue when you add to attributes _link_ key. When remove it, but leave tappableRegion, color is correct (not default blue) and text is tappable. But how remove underline and blue color from link in UILabel?

Didn't find any hints in examples.

**Comment by MrkFrnndz** [comment]
> Label is blue when you add to attributes _link_ key. When remove it, but leave tappableRegion, color is correct (not default blue) and text is tappable. But how remove underline and blue color from link in UILabel?
> 
> Didn't find any hints in examples.

This is also same scenario, Xcode 11.4, iOS 13, and Swift 5.2

**Comment by zacwest** [comment]
You don't need to use the `.link` attribute, but if you want to, you can specify `.foregroundColor` and `.underlineStyle` attributes which I believe override them.
