### ISSUE TITLE
there is support to implement the tappableLabel in uitableviewcell

### ISSUE THREAD

**Issue by luisrodrigo** [zacwest/ZSWTappableLabel#32]
How can I implement a tappableLabel inside a uitableviewcell? 
Inside uitableviewcel always enable the didselectrow.

**Comment by kmaschke85** [comment]
@luisrodrigo Simply implement method `tableView:willSelectRowAtIndexPath:`of `UITableViewDelegate`and return `nil`. With that the `UITableViewCell`won't be selected.
