### ISSUE TITLE
Delegate can optionally differentiate between tap and long-press

### ISSUE THREAD

**Issue by zacwest** [zacwest/ZSWTappableLabel#4]
It would be nice if a delegate could optionally support an additional method to receive long-press events (maybe with a defined interval on the label, since the internal `UILongPressGestureRecognizer` triggers immediately), e.g.:

``` objective-c
@protocol ZSWTappableLabelTapDelegate <NSObject>
- (void)tappableLabel:(ZSWTappableLabel *)tappableLabel
        tappedAtIndex:(NSInteger)idx
       withAttributes:(NSDictionary *)attributes;

@optional
- (void)tappableLabel:(ZSWTappableLabel *)tappableLabel
   longPressedAtIndex:(NSInteger)idx
       withAttributes:(NSDictionary *)attributes;
@end
```

This might be useful for delegates that wish to show a menu on long-press, and trigger another action immediately when tapped. For example, like Safari handles links.

**Comment by cerupcat** [comment]
Would love to see this as well.
