### ISSUE TITLE
Tappable region wrong when link is the only word on a new line

### ISSUE THREAD

**Issue by kevinvanmierlo** [zacwest/ZSWTappableLabel#42]
Hello! This library is great, but I found an issue which means I can't use this library right now.
The problem, as explained [here](https://stackoverflow.com/questions/46200027/uilabel-wrong-word-wrap-in-ios-11/63957498) is that since iOS 11 extra words will be placed on a new line instead of previous line if it means otherwise only one word would remain on the new line. 

I have created a test text to show what it does: "Testing various linking. Testing variously linking". It's not a real text, but shows the issue. The last word would normally be the only thing on the new line. But what I'm seeing is that the word before ("variously") is also pushed to the new line. The library doesn't know that and keeps the tappable regions in the same position. So If I press "variously" I get the link from "linking" and if I tap on the white space on the previous line I get the link from "variously". If you type an extra word so it has a minimum of two words on the second line it works as expected again. 

Below is a screenshot with 2 test scenarios. The first line is the default line as I'm using it. The second is the same default line, but I've added another "variously" word so it has two words on the second line. The second line work as expected. I click the link and it opens the correct one. However the first line doesn't work the right way. I've added a second screenshot in which you see where the clickareas are.

**Two test scenarios:**
![Screenshot 2021-02-05 at 14 38 48](https://user-images.githubusercontent.com/4548000/107041498-e0ede180-67c0-11eb-9c13-55fc90826e2d.png)

**Click areas on first test scenario (red is "variously" and blue is "linking"):**
![Screenshot 2021-02-05 at 14 38 48 clickareas](https://user-images.githubusercontent.com/4548000/107041520-e8ad8600-67c0-11eb-8c69-718f0532bcd5.png)

**Comment by zacwest** [comment]
Sounds about right. It is possible to use the NSLayoutManager's delegate to control line insertion to do what UILabel does here. This particular scenario -- where the last word is joined with a previous one -- is called orphan avoidance. The difficult part here is trying to emulate whatever logic UILabel is doing; I have been meaning to Hopper it to see if I can just steal it for now. Feel free to submit a PR for this!

**Comment by kevinvanmierlo** [comment]
Yeah I'm not exactly sure what the UILabel does. I've tried a few things to fix this issue, but didn't succeed. The weird thing is that a UILabel does this, but a UITextView doesn't. If I manage to fix this of course I will submit a PR, but I'm not sure if I'm capable. The problem is that the ZSWTappableLabel uses a NSLayoutManager and NSTextContainer and I know the UITextView uses this, but apparently the UILabel has some other logic inside.

**Comment by zacwest** [comment]
I believe UILabel uses the same TextKit things under the hood, it just also includes the orphan detection/avoidance. The `NSLayoutManagerDelegate` method `layoutManager(_:shouldBreakLineByWordBeforeCharacterAt:)` would be my guess at how it is accomplished, but it's possible it's happening at draw time too. It may be as simple as:

1. Set the NSLayoutManager delegate when creating it
2. Return `false` if it's the last space in the string, and there exist more spaces; possibly if and only if the word it's going to be dangling is too short.

I am guessing UILabel has slightly more complicated logic for (2).

**Comment by kevinvanmierlo** [comment]
Okay! Yeah that could be. But I am also guessing it's probably more complicated. And preferably the library uses the same method as the UILabel, that way it would always work. But that's probably not going to be possible.
