### ISSUE TITLE
String with "<xyz@gmail.com>" getting exception

### ISSUE THREAD

**Issue by prabhatVinsol** [zacwest/ZSWTappableLabel#43]
Please help me here that if the string contains "<>" getting the exception.
How to handle this situation.

**Comment by zacwest** [comment]
What exception are you receiving?

**Comment by prabhatVinsol** [comment]
@zacwest I have string "David Thrower - David <david@xyz.com>" and trying to get the attributed string using ZSWTaggedString and getting nil.

If I remove "<>" from the above string and it is working as expected.

How to handle these types of string which contain "<>"?

**Comment by zacwest** [comment]
I see, you are putting user-generated content into ZSWTaggedString, not this label class throwing the error. See the [Gotchas](https://github.com/zacwest/ZSWTaggedString#gotchas) section of the ZSWTaggedString README. Effectively: you want to run non-developer-written content using e.g. `ZSWTaggedString(format: "<something>%@</something>", ZSWEscapedStringForString(someString))`
