### ISSUE TITLE
Overloading text doesn't allow this to work in IB

### ISSUE THREAD

**Issue by HaloZero** [zacwest/ZSWTappableLabel#6]
I can't use ZSWTappableLabel in InterfaceBuilder because you override the text method. This prevents me from reading the text that I put in IB. Accessing the original text would be great if possible

Is there a strong reason for this?

**Comment by zacwest** [comment]
Are you talking about when you add a `ZSWTappableLabel` instance to a storyboard/nib, you're unable to edit the text inside like you would a normal `UILabel`?

This is more a non-feature of Interface Builder. For example, make any subclass of UILabel and stick it into your view; you won't be able to edit the text directly, even if you declare it `IB_DESIGNABLE`.

If you set text on a `ZSWTappableLabel` instance, you can read the text back. It overloads the setter method so it goes through the same attributed string path for all cases, which is easier to reason about.

**Comment by zacwest** [comment]
Ah, I see. If you drag out a _label_ and change the class, you can still configure the text. I'm going to close this in favor of a discussion in your pull request, #7.
