### ISSUE TITLE
Line spacing 

### ISSUE THREAD

**Issue by Ghousepasha-ios** [zacwest/ZSWTappableLabel#9]
How Can i add line spacing between two lines.
'label.attributedText = [[ZSWTaggedString stringWithString:string] attributedStringWithOptions:options];'

**Comment by zacwest** [comment]
Set the `NSParagraphStyle` for your string, for example:

```
// set up the paragraph style
NSMutableParagraphStyle *style = [NSMutableParagraphStyle defaultParagraphStyle];
style.lineSpacing = 5.0;
```

and add it to your `ZSWTaggedString`'s default attributes as an `NSParagraphStyleAttributeName` (or apply it to the whole range of your `NSMutableAttributedString`)
